### ISSUE TITLE
1.1.0 Midi timing instability

### ISSUE THREAD

**Issue by BestGitHubUsername** [Nornec/Midinous-Issues#28]
attached is two images, one of the Reason DAW sequencer where i recorded the MIDI data and one of Midinous network that was the source. both machines were running at the same tempo but not clocked together
![midinous midi instability source](https://user-images.githubusercontent.com/115594826/203441263-828e3eea-c97b-40f9-8ad3-1764e454a353.jpg)

i was actually testing to see if a POINT was monophonic so the network shows a POINT (duration 2 / repeat x4) set to relative transpose up an octave and the input of three Travellers coming from three POINTs each set to a note of CMaj Triad and recording the output into the reason sequencer to test if the notes truncate each other. happy to discover that a POINT is indeed polyphonic 
![midinous midi instability](https://user-images.githubusercontent.com/115594826/203441343-b6c6f285-954c-4249-877a-a16178db3cbf.jpg)

looking at the image of the recording (performed the test twice and bumped one version down a semitone to see them side by side)
the MIDI output from the POINT is a bit sloppy with regard to note on's and note length.

i performed the same test afterwards with Reason clocked from Midinous but observed the same inconsistencies

**Comment by Nornec** [comment]
I think everything is working okay here. I did measure a fluctuating latency between ±12ms which is roughly ten times faster than an eye blink. I don't know what scale you're using above but I did measure actual timing fluctuations between two separate recordings and although there was some latent output (and in some cases early, hence the ±), Midinous did not drift out of time with the DAW. I think this kind of MIDI recording into a daw can be easily quantized if that is desired. It's otherwise still likely more accurate than a seasoned musician.
