### ISSUE TITLE
 (Beta 1.05) Tutorial is no longer accessible after closing and reopening Midinous for the first time

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#3]
I just setup Midinous to run from the Beta 1.05 codebase and noticed the following:

1) Launch Midinous and NOTE intro splash page
2) Click Launch Tutorial and NOTE that the tutorial opens as expected.
3) Close Midinous and reopen.  NOTE that the intro splash page is no longer available and there is no visible way of relaunching the tutorial.

FWIW, I am running on Win10.

**Comment by Nornec** [comment]
Thanks for the report!
This is expected behavior. Once the welcome screen comes up (once per new version), it won't come up again. There's a flag in the code that is set to true (do_not_welcome) after the first open after an update.

Do you have any suggestions to make this feature better or more clear?

**Comment by worblyhead** [comment]
Another quick "workaround" is simply to File > Save As > MyFile to persist the tutorial easily between sessions.  However, a user runs the risk of dirtying and saving edits to that file and losing the tutorial until the next update/install.

**Comment by Nornec** [comment]
Yeah this is why the tutorial is "protected", i.e. in a different directory than the user directory, so that it doesn't get overwritten, but there's no point if people can't reach the tutorial again. So, I think I'll do what you suggest and move the do_not_welcome flag to a check box on the welcome screen.
