### ISSUE TITLE
1.1.0 - Possible race condition when stopping sequence (incl. Crash log)

### ISSUE THREAD

**Issue by ScreenPlane** [Nornec/Midinous-Issues#32]
Hi, here's the chrash log as requested. It chrashes randomly about every hour, mostly when the space bar is pressed to start the sequence. The midinous window disappears. In in almost all cases it will perform ok, with no chrash, when pressing space bar. 
[log.txt](https://github.com/Nornec/Midinous-Issues/files/11031403/log.txt)

**Comment by Nornec** [comment]
I have yet to experience this in the latest release unless the program was running abnormally slow with thousands upon thousands of points, travelers, and connections. Currently I don't think any user would want to have the program in that state, but please inform me and use the feedback feature or respond here if you encounter it with the latest release candidate (1.1.1)

**Comment by Nornec** [comment]
I just confirmed this was a crashing bug that was happening due to a race condition between the Performance thread and the drawing thread. I have mitigated this and it shouldn't happen even when the program is now pushed to the extreme. Look for the fixed crashing in the next Release Candidate (1.1.2).

**Comment by ScreenPlane** [comment]
Great! Busy this week, I hope I can have a look next week.
